/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.view.Super_Admin;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Properties;
import javax.swing.JOptionPane;
import org.connect.ConfigConstants;
import org.connect.ConfigUtil;
import org.ctrl.Parking_ctrl;

/**
 *
 * @author an
 */
public class Update_Clients extends javax.swing.JFrame {

    private String welcomeMessage;
    private static Parking_ctrl controller;
    private final String lname;
    private final String fname;
    private final String username;
    private final String email;
    private final String id;
    private final String password;

    /**
     * Creates new form Update_Clients
     *
     * @param fname
     * @param lname
     * @param username
     * @param email
     * @param id
     * @param password
     * @param welcomeMessage
     */
    public Update_Clients(String lname, String fname, String username, String email, String id, String password, String welcomeMessage) {
        initComponents();
        String filePath = ConfigConstants.DB_CONFIG_FILE_PATH;  // Chemin relatif vers le fichier de configuration
        Properties properties = ConfigUtil.loadProperties(filePath);

        String host = properties.getProperty("db.host");
        String user = properties.getProperty("db.user");
        String passwords = properties.getProperty("db.password");

        // Initialiser le contrôleur avec les valeurs chargées
        controller = new Parking_ctrl(host, user, passwords);
        this.lname = lname;
        this.fname = fname;
        this.username = username;
        this.email = email;
        this.id = id;
        this.password = password;
        this.welcomeMessage = welcomeMessage;
        updateDetails(lname, fname, username, email, password);
    }

    public static void updateDetails(String lname, String fname, String username, String email, String password) {
        if (l_name != null) {
            l_name.setText("1- Nom : " + lname);
        }
        if (f_name != null) {
            f_name.setText("2- Prénom : " + fname);
        }
        if (usr_name != null) {
            usr_name.setText("3- Nom d'utilisateur : " + username);
        }
        if (mail != null) {
            mail.setText("4- E-mail : " + email);
        }

    }

    private String hashPassword(String password) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] hashedBytes = md.digest(password.getBytes());

            StringBuilder sb = new StringBuilder();
            for (byte b : hashedBytes) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException("Erreur de hachage : " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        l_name = new javax.swing.JLabel();
        f_name = new javax.swing.JLabel();
        passwd = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        usr_name = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modifications");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(412, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_swing/Parking_Project/src/org/images/back_lg.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 50, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Élément à modfier");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));

        l_name.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        l_name.setForeground(new java.awt.Color(0, 0, 0));
        l_name.setText("1- Nom : ");
        l_name.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                dispose();
                Update_Lname_Clients UpdateLnameFrame = new Update_Lname_Clients(lname, fname, username, email, id, password, welcomeMessage);
                UpdateLnameFrame.setLocationRelativeTo(null);
                UpdateLnameFrame.setVisible(true);
            }
            @Override
            public void mouseEntered(MouseEvent e) {
                l_name.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                l_name.setForeground(new java.awt.Color(255, 51, 51));

            }

            @Override
            public void mouseExited(MouseEvent e) {
                l_name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                l_name.setForeground(new java.awt.Color(0, 0, 0));

            }
        });

        f_name.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        f_name.setForeground(new java.awt.Color(0, 0, 0));
        f_name.setText("2- Prénom : ");
        f_name.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                dispose();
                Update_Fname_Clients UpdateFnameFrame = new Update_Fname_Clients(lname, fname, username, email, id, password, welcomeMessage);
                UpdateFnameFrame.setLocationRelativeTo(null);
                UpdateFnameFrame.setVisible(true);
            }
            @Override
            public void mouseEntered(MouseEvent e) {
                f_name.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                f_name.setForeground(new java.awt.Color(255, 51, 51));

            }

            @Override
            public void mouseExited(MouseEvent e) {
                f_name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                f_name.setForeground(new java.awt.Color(0, 0, 0));

            }
        });

        passwd.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        passwd.setForeground(new java.awt.Color(0, 0, 0));
        passwd.setText("5- Réinitialiser le mot de passe ");
        passwd.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                dispose();
                Update_Password_Clients UpdatePasswordFrame = new Update_Password_Clients(lname, fname, username, email, id, password, welcomeMessage);
                UpdatePasswordFrame.setLocationRelativeTo(null);
                UpdatePasswordFrame.setVisible(true);

            }
            @Override
            public void mouseEntered(MouseEvent e) {
                passwd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                passwd.setForeground(new java.awt.Color(255, 51, 51));

            }

            @Override
            public void mouseExited(MouseEvent e) {
                passwd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                passwd.setForeground(new java.awt.Color(0, 0, 0));

            }
        });

        mail.setDisplayedMnemonic('M');
        mail.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        mail.setForeground(new java.awt.Color(0, 0, 0));
        mail.setText("4- E-mail : ");
        mail.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                dispose();
                Update_Email_Clients UpdateEmailFrame = new Update_Email_Clients(lname, fname, username, email, id, password, welcomeMessage);
                UpdateEmailFrame.setLocationRelativeTo(null);
                UpdateEmailFrame.setVisible(true);

            }
            @Override
            public void mouseEntered(MouseEvent e) {
                mail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                mail.setForeground(new java.awt.Color(255, 51, 51));

            }

            @Override
            public void mouseExited(MouseEvent e) {
                mail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                mail.setForeground(new java.awt.Color(0, 0, 0));
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Liberation Sans", 0, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("Retour");
        jButton2.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                jButton2.setBackground(new java.awt.Color(255, 51, 51));
                jButton2.setForeground(new java.awt.Color(0, 0,0));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                jButton2.setBackground(new java.awt.Color(0, 0, 0));
                jButton2.setForeground(new java.awt.Color(255, 51, 51));
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        usr_name.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        usr_name.setForeground(new java.awt.Color(0, 0, 0));
        usr_name.setText("3- Nom d'utilisateur : ");
        usr_name.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                dispose();
                Update_Username_Clients UpdateUnameFrame = new Update_Username_Clients(lname, fname, username, email, id, password, welcomeMessage);
                UpdateUnameFrame.setLocationRelativeTo(null);
                UpdateUnameFrame.setVisible(true);

            }
            @Override
            public void mouseEntered(MouseEvent e) {
                usr_name.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                usr_name.setForeground(new java.awt.Color(255, 51, 51));

            }

            @Override
            public void mouseExited(MouseEvent e) {
                usr_name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                usr_name.setForeground(new java.awt.Color(0, 0, 0));

            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f_name)
                            .addComponent(l_name)
                            .addComponent(mail)
                            .addComponent(usr_name)
                            .addComponent(passwd))
                        .addGap(149, 149, 149))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75)
                .addComponent(l_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(f_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usr_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mail)
                .addGap(18, 18, 18)
                .addComponent(passwd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        All_Client AllClientFrame = new All_Client(welcomeMessage);
        AllClientFrame.setVisible(true);
        AllClientFrame.pack();
        AllClientFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        String welcomeMessage = "";
        /* Create and display the form */
        String finalMessage = welcomeMessage;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Clients("", "", "", "", "", "", finalMessage).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel f_name;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private static javax.swing.JLabel l_name;
    private static javax.swing.JLabel mail;
    private static javax.swing.JLabel passwd;
    private static javax.swing.JLabel usr_name;
    // End of variables declaration//GEN-END:variables
}
