/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.view.Super_Admin;

import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Properties;
import javax.swing.ImageIcon;
import org.connect.ConfigConstants;
import org.connect.ConfigUtil;
import org.ctrl.Parking_ctrl;

/**
 *
 * @author an
 */
public class Update_Vehicles extends javax.swing.JFrame {

    private static String welcomeMessage;
    private static Parking_ctrl controller;
    private static String brand;
    private static String model;
    private static String plate;
    private static String year;
    private static String id;
    private static String image;
    private static String price;
    private static String loan_price;

    /**
     * Creates new form Update_Vehicles
     *
     * @param brand
     * @param model
     * @param plate
     * @param year
     * @param id
     * @param image
     * @param price
     * @param loan_price
     * @param welcomeMessage
     */
    public Update_Vehicles(String brand, String model, String plate, String year, String id, String image, String price, String loan_price, String welcomeMessage) {
        initComponents();
        String filePath = ConfigConstants.DB_CONFIG_FILE_PATH;  // Chemin relatif vers le fichier de configuration
        Properties properties = ConfigUtil.loadProperties(filePath);

        String host = properties.getProperty("db.host");
        String user = properties.getProperty("db.user");
        String passwords = properties.getProperty("db.password");

        // Initialiser le contrôleur avec les valeurs chargées
        controller = new Parking_ctrl(host, user, passwords);
        this.brand = brand;
        this.model = model;
        this.plate = plate;
        this.year = year;
        this.id = id;
        this.image = image;
        this.price = price;
        this.loan_price = loan_price;
        this.welcomeMessage = welcomeMessage;
        updateDetails(brand, model, plate, year, image, price, loan_price);
    }

    public static void updateDetails(String brand, String model, String plate, String year, String image, String price, String loan_price) {
        if (brand_veh != null) {
            brand_veh.setText("1- Marque : " + brand);
        }
        if (model_veh != null) {
            model_veh.setText("2- Modèle : " + model);
        }
        if (plate_veh != null) {
            plate_veh.setText("3- Plaque : " + plate);
        }
        if (year_veh != null) {
            year_veh.setText("4- Année : " + year);
        }

        if (img_veh != null) {
            // Configurer JLabel pour afficher le texte au-dessus de l'image
            

            try {
                ImageIcon originalImageIcon = new ImageIcon(image);
                Image originalImage = originalImageIcon.getImage();
                Image scaledImage = originalImage.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
                img_veh.setIcon(new ImageIcon(scaledImage));
            } catch (Exception e) {
                img_veh.setText("5- Image : Image non disponible");
            }
            

        }

        if (price_veh != null) {
            price_veh.setText("6- Prix(vendre) : " + price + " $");
        }

        if (loan_price_veh != null) {
            loan_price_veh.setText("7- Prix(location) : " + loan_price + " $");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        brand_veh = new javax.swing.JLabel();
        model_veh = new javax.swing.JLabel();
        year_veh = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        plate_veh = new javax.swing.JLabel();
        img_veh = new javax.swing.JLabel();
        price_veh = new javax.swing.JLabel();
        loan_price_veh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(412, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_swing/Parking_Project/src/org/images/back_lg.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 250, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Élément à modfier");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));

        brand_veh.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        brand_veh.setForeground(new java.awt.Color(0, 0, 0));
        brand_veh.setText("1- Marque : ");
        brand_veh.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                dispose();
                Update_Vehicles_Brand UpdateVehiclesBrandFrame = new Update_Vehicles_Brand(brand, model, plate, year, id, image, price, loan_price, welcomeMessage);
                UpdateVehiclesBrandFrame.setLocationRelativeTo(null);
                UpdateVehiclesBrandFrame.setVisible(true);

            }
            @Override
            public void mouseEntered(MouseEvent e) {
                brand_veh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                brand_veh.setForeground(new java.awt.Color(255, 51, 51));

            }

            @Override
            public void mouseExited(MouseEvent e) {
                brand_veh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                brand_veh.setForeground(new java.awt.Color(0, 0, 0));

            }
        });

        model_veh.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        model_veh.setForeground(new java.awt.Color(0, 0, 0));
        model_veh.setText("2- Modèle : ");
        model_veh.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                dispose();
                Update_Vehicles_Model UpdateVehiclesModelFrame = new Update_Vehicles_Model(brand, model, plate, year, id, image, price, loan_price, welcomeMessage);
                UpdateVehiclesModelFrame.setLocationRelativeTo(null);
                UpdateVehiclesModelFrame.setVisible(true);

            }
            @Override
            public void mouseEntered(MouseEvent e) {
                model_veh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                model_veh.setForeground(new java.awt.Color(255, 51, 51));

            }

            @Override
            public void mouseExited(MouseEvent e) {
                model_veh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                model_veh.setForeground(new java.awt.Color(0, 0, 0));

            }
        });

        year_veh.setDisplayedMnemonic('M');
        year_veh.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        year_veh.setForeground(new java.awt.Color(0, 0, 0));
        year_veh.setText("4- Année : ");
        year_veh.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                dispose();
                Update_Vehicles_Year UpdateVehiclesYearFrame = new Update_Vehicles_Year(brand, model, plate, year, id, image, price, loan_price, welcomeMessage);
                UpdateVehiclesYearFrame.setLocationRelativeTo(null);
                UpdateVehiclesYearFrame.setVisible(true);

            }
            @Override
            public void mouseEntered(MouseEvent e) {
                year_veh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                year_veh.setForeground(new java.awt.Color(255, 51, 51));

            }

            @Override
            public void mouseExited(MouseEvent e) {
                year_veh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                year_veh.setForeground(new java.awt.Color(0, 0, 0));
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Liberation Sans", 0, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("Retour");
        jButton2.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                jButton2.setBackground(new java.awt.Color(255, 51, 51));
                jButton2.setForeground(new java.awt.Color(0, 0,0));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                jButton2.setBackground(new java.awt.Color(0, 0, 0));
                jButton2.setForeground(new java.awt.Color(255, 51, 51));
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        plate_veh.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        plate_veh.setForeground(new java.awt.Color(0, 0, 0));
        plate_veh.setText("3- Plaque : ");
        plate_veh.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                dispose();
                Update_Vehicles_Plate UpdateVehiclesPlateFrame = new Update_Vehicles_Plate(brand, model, plate, year, id, image, price, loan_price, welcomeMessage);
                UpdateVehiclesPlateFrame.setLocationRelativeTo(null);
                UpdateVehiclesPlateFrame.setVisible(true);

            }
            @Override
            public void mouseEntered(MouseEvent e) {
                plate_veh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                plate_veh.setForeground(new java.awt.Color(255, 51, 51));

            }

            @Override
            public void mouseExited(MouseEvent e) {
                plate_veh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                plate_veh.setForeground(new java.awt.Color(0, 0, 0));

            }
        });

        img_veh.setDisplayedMnemonic('M');
        img_veh.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        img_veh.setForeground(new java.awt.Color(0, 0, 0));
        img_veh.setText("5- Image : ");
        img_veh.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        img_veh.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        img_veh.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                dispose();
                Update_Vehicles_Image UpdateVehiclesImageFrame = new Update_Vehicles_Image(brand, model, plate, year, id, image, price, loan_price, welcomeMessage);
                UpdateVehiclesImageFrame.setLocationRelativeTo(null);
                UpdateVehiclesImageFrame.setVisible(true);

            }
            @Override
            public void mouseEntered(MouseEvent e) {
                img_veh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                img_veh.setForeground(new java.awt.Color(255, 51, 51));

            }

            @Override
            public void mouseExited(MouseEvent e) {
                img_veh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                img_veh.setForeground(new java.awt.Color(0, 0, 0));
            }
        });

        price_veh.setDisplayedMnemonic('M');
        price_veh.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        price_veh.setForeground(new java.awt.Color(0, 0, 0));
        price_veh.setText("6- Prix (vendre)");
        price_veh.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                dispose();
                Update_Vehicles_Price UpdateVehiclesPriceFrame = new Update_Vehicles_Price(brand, model, plate, year, id, image, price, loan_price, welcomeMessage);
                UpdateVehiclesPriceFrame.setLocationRelativeTo(null);
                UpdateVehiclesPriceFrame.setVisible(true);

            }
            @Override
            public void mouseEntered(MouseEvent e) {
                price_veh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                price_veh.setForeground(new java.awt.Color(255, 51, 51));

            }

            @Override
            public void mouseExited(MouseEvent e) {
                price_veh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                price_veh.setForeground(new java.awt.Color(0, 0, 0));
            }
        });

        loan_price_veh.setDisplayedMnemonic('M');
        loan_price_veh.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        loan_price_veh.setForeground(new java.awt.Color(0, 0, 0));
        loan_price_veh.setText("7- Prix (location)");
        loan_price_veh.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                dispose();
                Update_Vehicles_LoanPrice UpdateVehiclesLoanPriceFrame = new Update_Vehicles_LoanPrice(brand, model, plate, year, id, image, price, loan_price, welcomeMessage);
                UpdateVehiclesLoanPriceFrame.setLocationRelativeTo(null);
                UpdateVehiclesLoanPriceFrame.setVisible(true);

            }
            @Override
            public void mouseEntered(MouseEvent e) {
                loan_price_veh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                loan_price_veh.setForeground(new java.awt.Color(255, 51, 51));

            }

            @Override
            public void mouseExited(MouseEvent e) {
                loan_price_veh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                loan_price_veh.setForeground(new java.awt.Color(0, 0, 0));
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addGap(100, 100, 100))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(model_veh)
                            .addComponent(brand_veh)
                            .addComponent(year_veh)
                            .addComponent(plate_veh)
                            .addComponent(img_veh)
                            .addComponent(price_veh)
                            .addComponent(loan_price_veh))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brand_veh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(model_veh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(plate_veh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(year_veh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(img_veh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(price_veh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loan_price_veh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        All_Vehicles AllVehiclesFrame = new All_Vehicles(welcomeMessage);
        AllVehiclesFrame.setVisible(true);
        AllVehiclesFrame.pack();
        AllVehiclesFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Vehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Vehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Vehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Vehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        String welcomeMessage = "";

        /* Create and display the form */
        String finalMessage = welcomeMessage;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Vehicles("", "", "", "", "", "", "", "", finalMessage).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel brand_veh;
    private static javax.swing.JLabel img_veh;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private static javax.swing.JLabel loan_price_veh;
    private static javax.swing.JLabel model_veh;
    private static javax.swing.JLabel plate_veh;
    private static javax.swing.JLabel price_veh;
    private static javax.swing.JLabel year_veh;
    // End of variables declaration//GEN-END:variables
}
